#!/bin/bash

# Monster Sprite Generation Script
# This script provides commands and prompts for generating monster sprites

echo "🎮 CareQuest Monster Sprite Generator"
echo "======================================"
echo ""
echo "📋 Monster List:"
echo ""
echo "COMMON MONSTERS:"
echo "1. Anxiety Goblin (Blue/Purple)"
echo "2. Stress Slime (Green/Yellow)"
echo "3. Burnout Beast (Orange/Red)"
echo "4. Procrastination Imp (Pink/Purple)"
echo "5. Loneliness Wraith (Gray/Blue)"
echo ""
echo "BOSSES:"
echo "6. Exam Week Demon (Red/Purple)"
echo "7. Thesis Dragon (Blue/Gold)"
echo "8. Social Pressure Titan (Multi-color)"
echo "9. Perfectionism Hydra (Purple/Gold)"
echo "10. Imposter Syndrome Leviathan (Dark Blue/Black)"
echo ""
echo "========================================="
echo "🎨 RECOMMENDED TOOLS:"
echo "========================================="
echo ""
echo "Option 1: Leonardo.ai (FREE - Best for game sprites)"
echo "  - Visit: https://leonardo.ai"
echo "  - Model: 'Leonardo Pixel Art' or 'Pixel Art XL'"
echo "  - Resolution: 512x512"
echo "  - Style: 'pixel art, game sprite, transparent background'"
echo ""
echo "Option 2: Stable Diffusion (FREE - Local)"
echo "  - Install: https://github.com/AUTOMATIC1111/stable-diffusion-webui"
echo "  - Model: 'pixel-art-diffusion' from HuggingFace"
echo "  - Add: 'transparent background, game sprite' to all prompts"
echo ""
echo "Option 3: DALL-E 3 via ChatGPT Plus"
echo "  - Visit: https://chat.openai.com"
echo "  - Use prompts below, add: 'transparent background, game sprite'"
echo ""
echo "Option 4: Free Assets (Instant)"
echo "  - itch.io: https://itch.io/game-assets/free"
echo "  - OpenGameArt: https://opengameart.org"
echo "  - Kenney: https://kenney.nl/assets"
echo ""
echo "========================================="
echo "📝 COPY-PASTE PROMPTS:"
echo "========================================="
echo ""
echo "--- ANXIETY GOBLIN ---"
echo "cute anxious goblin character, pixel art style, blue and purple colors,"
echo "worried expression, small and round body, soft edges, game sprite,"
echo "transparent background, mental health theme, friendly not scary, 512x512px"
echo ""
echo "--- STRESS SLIME ---"
echo "tired green slime creature, pixel art style, green-yellow gradient,"
echo "exhausted droopy eyes, melting blob shape, game sprite,"
echo "transparent background, cute and sympathetic, 512x512px"
echo ""
echo "--- BURNOUT BEAST ---"
echo "exhausted wolf creature, pixel art style, orange-red colors,"
echo "tired expression, slouched posture, flames on body, game sprite,"
echo "transparent background, sympathetic not scary, 512x512px"
echo ""
echo "--- PROCRASTINATION IMP ---"
echo "lazy mischievous imp, pixel art style, pink-purple colors,"
echo "sleepy expression, sitting or laying down, clock elements, game sprite,"
echo "transparent background, cute and relatable, 512x512px"
echo ""
echo "--- LONELINESS WRAITH ---"
echo "sad ghost-like wraith, pixel art style, gray-blue colors,"
echo "lonely expression, translucent floating body, soft glow, game sprite,"
echo "transparent background, melancholic but kind, 512x512px"
echo ""
echo "--- EXAM WEEK DEMON (BOSS) ---"
echo "large demon boss with books and papers, pixel art style, red-purple,"
echo "intense but not scary expression, holding stack of books, pencils, game boss sprite,"
echo "transparent background, academic theme, stylized cartoon, 512x512px"
echo ""
echo "--- THESIS DRAGON (BOSS) ---"
echo "majestic paper dragon, pixel art style, blue-gold colors,"
echo "made of pages and books, wise expression, flying pose, papers swirling around,"
echo "transparent background, game boss sprite, 512x512px"
echo ""
echo "--- SOCIAL PRESSURE TITAN (BOSS) ---"
echo "towering giant with multiple faces, pixel art style, multi-colored,"
echo "crowd of people forming body, expressions of expectation, game boss sprite,"
echo "transparent background, imposing but not evil, 512x512px"
echo ""
echo "--- PERFECTIONISM HYDRA (BOSS) ---"
echo "multi-headed hydra boss, pixel art style, purple-gold colors,"
echo "each head examining something critically, magnifying glasses, ruler elements,"
echo "transparent background, game boss sprite, 512x512px"
echo ""
echo "--- IMPOSTER SYNDROME LEVIATHAN (BOSS) ---"
echo "massive serpent in shadows, pixel art style, dark blue-black,"
echo "masks and question marks around it, mysterious appearance, game boss sprite,"
echo "transparent background, dramatic but not terrifying, 512x512px"
echo ""
echo "========================================="
echo "🔧 POST-PROCESSING:"
echo "========================================="
echo ""
echo "1. Remove backgrounds (if not transparent):"
echo "   - remove.bg (https://remove.bg)"
echo "   - Photopea (https://photopea.com) - Free Photoshop alternative"
echo ""
echo "2. Resize to standard dimensions:"
echo "   - Common monsters: 256x256px"
echo "   - Bosses: 512x512px"
echo "   - Use: ImageMagick or online tools"
echo ""
echo "3. Optimize file size:"
echo "   - TinyPNG (https://tinypng.com)"
echo "   - Squoosh (https://squoosh.app)"
echo ""
echo "========================================="
echo "📦 SAVE TO:"
echo "frontend/public/assets/monsters/"
echo ""
echo "Naming convention:"
echo "  - anxiety-goblin.png"
echo "  - stress-slime.png"
echo "  - exam-week-demon.png"
echo "  etc."
echo ""
echo "========================================="
echo "✅ After generating sprites, update:"
echo "frontend/src/app/carequest/(hub)/constants.ts"
echo ""
echo "Change icon values from text to paths:"
echo "  icon: '/assets/monsters/anxiety-goblin.png'"
echo ""
echo "========================================="
