"""Aggregated admin schema exports."""
from .analytics import (
    AnalyticsResponse,
    CohortHotspot,
    CohortHotspotsResponse,
    InterventionSummary,
    InterventionTotals,
    PredictiveSignalPayload,
    PredictiveSignalsResponse,
    SeverityDelta,
    TriageMetricsInsight,
    TopCampaignSummary,
)
from .appointments import (
    AppointmentResponse,
    AppointmentUpdate,
    AppointmentUser,
    TherapistScheduleCreate,
    TherapistScheduleResponse,
    TherapistScheduleUpdate,
    TherapistSummary,
)
from app.schemas.counselor import (
    CounselorResponse,
    CounselorListResponse,
    CounselorListItem,
    CounselorAvailabilityToggle,
    CounselorStats,
)
from .content_resources import (
    ContentResourceCreate,
    ContentResourceItem,
    ContentResourceResponse,
)
from .conversations import (
    ConversationDetailResponse,
    ConversationListItem,
    ConversationRiskAssessmentListResponse,
    ConversationRiskAssessmentResponse,
    ConversationAssessmentTriggerRequest,
    ConversationStats,
    ConversationsResponse,
    SessionDetailResponse,
    SessionListItem,
    SessionListResponse,
    SessionUser,
)
from .dashboard import AppointmentSummary, FeedbackSummary
from .interventions import (
    CampaignMetrics,
    CampaignSummary,
    ExecutionSummary,
    InterventionCampaignCreate,
    InterventionCampaignListResponse,
    InterventionCampaignResponse,
    InterventionCampaignUpdate,
    InterventionExecutionListResponse,
    InterventionExecutionResponse,
    InterventionExecutionUpdate,
    InterventionOverview,
    InterventionSettings,
    InterventionSettingsUpdate,
    ManualInterventionCreate,
    QueueItem,
)
from .system import (
    SystemSettingItem,
    SystemSettingsCategory,
    SystemSettingsResponse,
)
from .flags import (
    FlagCreate,
    FlagResponse,
    FlagUpdate,
    FlagsBulkCloseRequest,
    FlagsBulkTagRequest,
    FlagsSummary,
)

from .profile import (
    AdminProfileResponse,
    AdminProfileUpdateRequest,
    AdminPasswordChangeRequest,
    AdminPasswordChangeResponse,
)
from .users import (
    AdminCreateUserRequest,
    AdminCreateUserResponse,
    AdminUpdateUserRequest,
    AdminUserLogItem,
    UserDetailResponse,
    UserListItem,
    UserStats,
    UsersResponse,
)
from .agent_users import AgentUserSummary, AgentUserCreate, AgentUserUpdateRole
from .triage import (
    SeverityBreakdown,
    ProcessingMetrics,
    RiskTrendPoint,
    SlaMetrics,
    TriageCasePreview,
    TriageOverview,
    TriageAssessmentItem,
    TriageAssessmentListResponse,
    TriageTestRequest,
    TriageTestResponse,
)
from .quests import (
    QuestTemplateCreate,
    QuestTemplateListResponse,
    QuestTemplateResponse,
    QuestTemplateUpdate,
)
from .autopilot import (
    AutopilotActionResponse,
    AutopilotActionListResponse,
    AutopilotActionReviewRequest,
    AutopilotActionReviewResponse,
)

__all__ = [
    "AnalyticsResponse",
    "CohortHotspot",
    "CohortHotspotsResponse",
    "InterventionSummary",
    "InterventionTotals",
    "PredictiveSignalPayload",
    "PredictiveSignalsResponse",
    "SeverityDelta",
    "TriageMetricsInsight",
    "TopCampaignSummary",
    "AppointmentResponse",
    "AppointmentUpdate",
    "AppointmentUser",
    "CounselorResponse",
    "CounselorListResponse",
    "CounselorListItem",
    "CounselorAvailabilityToggle",
    "CounselorStats",

    "TherapistSummary",
    "TherapistScheduleCreate",
    "TherapistScheduleResponse",
    "TherapistScheduleUpdate",
    "ContentResourceCreate",
    "ContentResourceItem",
    "ContentResourceResponse",
    "ConversationDetailResponse",
    "ConversationListItem",
    "ConversationRiskAssessmentListResponse",
    "ConversationRiskAssessmentResponse",
    "ConversationAssessmentTriggerRequest",
    "ConversationStats",
    "ConversationsResponse",
    "SessionDetailResponse",
    "SessionListItem",
    "SessionListResponse",
    "SessionUser",
    "AppointmentSummary",
    "FeedbackSummary",
    "CampaignMetrics",
    "CampaignSummary",
    "ExecutionSummary",
    "InterventionCampaignCreate",
    "InterventionCampaignListResponse",
    "InterventionCampaignResponse",
    "InterventionCampaignUpdate",
    "InterventionExecutionListResponse",
    "InterventionExecutionResponse",
    "InterventionExecutionUpdate",
    "InterventionOverview",
    "InterventionSettings",
    "InterventionSettingsUpdate",
    "ManualInterventionCreate",
    "QueueItem",
    "SystemSettingItem",
    "SystemSettingsCategory",
    "SystemSettingsResponse",
    "FlagCreate",
    "FlagResponse",
    "FlagUpdate",
    "FlagsBulkCloseRequest",
    "FlagsBulkTagRequest",
    "FlagsSummary",
    "AdminProfileResponse",
    "AdminProfileUpdateRequest",
    "AdminPasswordChangeRequest",
    "AdminPasswordChangeResponse",
    "UserDetailResponse",
    "UserListItem",
    "UserStats",
    "UsersResponse",
    "AdminCreateUserRequest",
    "AdminCreateUserResponse",
    "AdminUpdateUserRequest",
    "AdminUserLogItem",
    "AgentUserSummary",
    "AgentUserCreate",
    "AgentUserUpdateRole",
    "SeverityBreakdown",
    "ProcessingMetrics",
    "RiskTrendPoint",
    "SlaMetrics",
    "TriageCasePreview",
    "TriageOverview",
    "TriageAssessmentItem",
    "TriageAssessmentListResponse",
    "TriageTestRequest",
    "TriageTestResponse",
    "QuestTemplateCreate",
    "QuestTemplateListResponse",
    "QuestTemplateResponse",
    "QuestTemplateUpdate",
    "AutopilotActionResponse",
    "AutopilotActionListResponse",
    "AutopilotActionReviewRequest",
    "AutopilotActionReviewResponse",
]




