"""A Mako template for creating Alembic migration scripts.

This template is used by the ``alembic revision`` command to generate
a new migration script.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc6e6a0fe8c'
down_revision = '1b976f930da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'tweets' in inspector.get_table_names():
        op.alter_column('tweets', 'text',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'tweets' in inspector.get_table_names():
        op.alter_column('tweets', 'text',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=False)
    # ### end Alembic commands ###
