"""A Mako template for creating Alembic migration scripts.

This template is used by the ``alembic revision`` command to generate
a new migration script.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612167b98a55'
down_revision = '1970e622e299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if analytics_reports table exists before altering it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'analytics_reports' in inspector.get_table_names():
        op.add_column('analytics_reports', sa.Column('window_start', sa.DateTime(), nullable=True))
        op.add_column('analytics_reports', sa.Column('window_end', sa.DateTime(), nullable=True))
        op.add_column('analytics_reports', sa.Column('baseline_snapshot', sa.JSON(), nullable=True))
        op.add_column('analytics_reports', sa.Column('resource_engagement', sa.JSON(), nullable=True))
        op.add_column('analytics_reports', sa.Column('intervention_outcomes', sa.JSON(), nullable=True))
        op.add_column('analytics_reports', sa.Column('topic_excerpts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_reports', 'topic_excerpts')
    op.drop_column('analytics_reports', 'intervention_outcomes')
    op.drop_column('analytics_reports', 'resource_engagement')
    op.drop_column('analytics_reports', 'baseline_snapshot')
    op.drop_column('analytics_reports', 'window_end')
    op.drop_column('analytics_reports', 'window_start')
    # ### end Alembic commands ###
