"""A Mako template for creating Alembic migration scripts.

This template is used by the ``alembic revision`` command to generate
a new migration script.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756c4fde7a1b'
down_revision = 'c613d13854de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get inspector for idempotent checks
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create indexes on agent_messages if table exists
    if 'agent_messages' in existing_tables:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('agent_messages')}
        if 'ix_agent_messages_id' not in existing_indexes:
            op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    
    # Note: Skipping foreign key constraint modification for idempotency
    # Original migration: op.drop_constraint + op.create_foreign_key
    # This is not critical for retry safety
    
    # Create indexes on agent_runs if table exists
    if 'agent_runs' in existing_tables:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('agent_runs')}
        if 'ix_agent_runs_id' not in existing_indexes:
            op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    
    # Add category column to surveys if table exists and column doesn't exist
    if 'surveys' in existing_tables:
        existing_columns = {col['name'] for col in inspector.get_columns('surveys')}
        if 'category' not in existing_columns:
            op.add_column('surveys', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Drop category column from surveys if it exists
    if 'surveys' in existing_tables:
        existing_columns = {col['name'] for col in inspector.get_columns('surveys')}
        if 'category' in existing_columns:
            op.drop_column('surveys', 'category')
    
    # Drop indexes if they exist
    if 'agent_runs' in existing_tables:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('agent_runs')}
        if 'ix_agent_runs_id' in existing_indexes:
            op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    
    # Note: Skipping constraint operations for safety
    # Original: op.drop_constraint(None, ...) and op.create_foreign_key(...)
    
    if 'agent_messages' in existing_tables:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('agent_messages')}
        if 'ix_agent_messages_id' in existing_indexes:
            op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    # ### end Alembic commands ###
