"""Add cbt_module_steps table

Revision ID: e574b9ff31e8
Revises: f2131696e189
Create Date: 2025-09-12 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e574b9ff31e8'
down_revision = 'f2131696e189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get inspector for idempotent checks
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create cbt_module_steps table if it doesn't exist
    if 'cbt_module_steps' not in existing_tables:
        op.create_table('cbt_module_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_input_type', sa.String(length=50), nullable=True),
    sa.Column('user_input_variable', sa.String(length=100), nullable=True),
    sa.Column('feedback_prompt', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('tool_to_run', sa.String(length=100), nullable=True),
    sa.Column('is_skippable', sa.Boolean(), nullable=False),
    sa.Column('delay_after_ms', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['cbt_modules.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['cbt_module_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_cbt_module_steps_id'), 'cbt_module_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cbt_module_steps_id'), table_name='cbt_module_steps')
    op.drop_table('cbt_module_steps')
    # ### end Alembic commands ###
