"""Add cbt_modules table

Revision ID: f2131696e189
Revises: 2e01d72c41b0
Create Date: 2025-09-12 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2131696e189'
down_revision = '2e01d72c41b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get inspector for idempotent checks
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create cbt_modules table if it doesn't exist
    if 'cbt_modules' not in existing_tables:
        op.create_table('cbt_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_cbt_modules_id'), 'cbt_modules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cbt_modules_id'), table_name='cbt_modules')
    op.drop_table('cbt_modules')
    # ### end Alembic commands ###
