"""add pad dimensions

Revision ID: c11f5f5333b1
Revises: c9f3e2a1b7d4
Create Date: 2026-03-27 16:15:46.869587

IMPORTANT: All migrations should be IDEMPOTENT.
- Use migration_helpers for existence checks
- Never assume table/column state
- Test both upgrade() and downgrade()
- Document any data transformations
"""

from __future__ import annotations

from typing import Any

from alembic import context, op
import sqlalchemy as sa


# Import migration helpers for idempotent operations
try:
    from alembic import migration_helpers as mh
except ImportError:
    # Fallback if helpers not available
    mh = None

# revision identifiers, used by Alembic.
revision: str = 'c11f5f5333b1'
down_revision: str | None = 'c9f3e2a1b7d4'
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | str | None = None


def upgrade() -> None:
    """Apply schema (and optional data) upgrades."""
    schema_upgrade()
    if _should_run_data_migrations():
        data_upgrade()


def downgrade() -> None:
    """Revert schema (and optional data) upgrades."""
    if _should_run_data_migrations():
        data_downgrade()
    schema_downgrade()


def schema_upgrade() -> None:
    """
    Apply schema changes with idempotent checks.
    
    Example patterns:
    
    # Creating tables
    if mh and not mh.table_exists('my_table'):
        op.create_table('my_table', ...)
    
    # Adding columns
    if mh and not mh.column_exists('my_table', 'my_column'):
        op.add_column('my_table', sa.Column('my_column', ...))
    
    # Creating indexes
    if mh and not mh.index_exists('idx_name', 'my_table'):
        op.create_index('idx_name', 'my_table', ['column'])
    
    # Or use helper functions directly:
    if mh:
        mh.add_column_if_not_exists('my_table', sa.Column('my_column', ...))
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_badge_issuances_id'), 'badge_issuances', ['id'], unique=False)
    op.create_index(op.f('ix_badge_templates_id'), 'badge_templates', ['id'], unique=False)
    op.add_column('conversation_risk_assessments', sa.Column('pleasure', sa.Float(), nullable=True))
    op.add_column('conversation_risk_assessments', sa.Column('arousal', sa.Float(), nullable=True))
    op.add_column('conversation_risk_assessments', sa.Column('dominance', sa.Float(), nullable=True))
    op.add_column('journal_entries', sa.Column('valence', sa.Float(), nullable=True))
    op.add_column('journal_entries', sa.Column('arousal', sa.Float(), nullable=True))
    op.create_index(op.f('ix_retention_cohort_daily_id'), 'retention_cohort_daily', ['id'], unique=False)
    op.drop_index(op.f('ix_user_ai_memory_facts_created_at'), table_name='user_ai_memory_facts')
    op.alter_column('user_clinical_records', 'therapy_notes',
               existing_type=sa.TEXT(),
               comment='Non-sensitive therapy notes / context (avoid detailed clinical transcripts)',
               existing_nullable=True)
    op.alter_column('user_daily_activity', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='api|web|mobile|unknown',
               existing_nullable=True)
    op.create_index(op.f('ix_user_daily_activity_id'), 'user_daily_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.alter_column('user_preferences', 'communication_preferences',
               existing_type=sa.TEXT(),
               comment='User communication preferences (free text; migrated from users.communication_preferences)',
               existing_nullable=True)
    op.alter_column('user_preferences', 'interface_preferences',
               existing_type=sa.TEXT(),
               comment='User interface preferences (free text; migrated from users.interface_preferences)',
               existing_nullable=True)
    op.alter_column('user_profiles', 'telegram_username',
               existing_type=sa.VARCHAR(length=100),
               comment="Telegram username without '@' (e.g., 'john_doe')",
               existing_nullable=True)
    op.drop_constraint(op.f('uq_users_ocid_username'), 'users', type_='unique')
    # ### end Alembic commands ###


def schema_downgrade() -> None:
    """
    Revert schema changes with idempotent checks.
    
    Example patterns:
    
    # Dropping columns
    if mh and mh.column_exists('my_table', 'my_column'):
        op.drop_column('my_table', 'my_column')
    
    # Dropping tables
    if mh and mh.table_exists('my_table'):
        op.drop_table('my_table')
    
    # Or use helper functions:
    if mh:
        mh.drop_column_if_exists('my_table', 'my_column')
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_ocid_username'), 'users', ['ocid_username'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_profiles', 'telegram_username',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Telegram username without '@' (e.g., 'john_doe')",
               existing_nullable=True)
    op.alter_column('user_preferences', 'interface_preferences',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User interface preferences (free text; migrated from users.interface_preferences)',
               existing_nullable=True)
    op.alter_column('user_preferences', 'communication_preferences',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User communication preferences (free text; migrated from users.communication_preferences)',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_daily_activity_id'), table_name='user_daily_activity')
    op.alter_column('user_daily_activity', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='api|web|mobile|unknown',
               existing_nullable=True)
    op.alter_column('user_clinical_records', 'therapy_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Non-sensitive therapy notes / context (avoid detailed clinical transcripts)',
               existing_nullable=True)
    op.create_index(op.f('ix_user_ai_memory_facts_created_at'), 'user_ai_memory_facts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_retention_cohort_daily_id'), table_name='retention_cohort_daily')
    op.drop_column('journal_entries', 'arousal')
    op.drop_column('journal_entries', 'valence')
    op.drop_column('conversation_risk_assessments', 'dominance')
    op.drop_column('conversation_risk_assessments', 'arousal')
    op.drop_column('conversation_risk_assessments', 'pleasure')
    op.drop_index(op.f('ix_badge_templates_id'), table_name='badge_templates')
    op.drop_index(op.f('ix_badge_issuances_id'), table_name='badge_issuances')
    # ### end Alembic commands ###


def data_upgrade() -> None:
    """
    Idempotent data migrations executed with --x data=true.
    
    Use this for:
    - Populating new columns with computed values
    - Migrating data between tables
    - Seeding initial data
    
    IMPORTANT: Make this idempotent by checking for existing data first.
    
    Example:
        conn = op.get_bind()
        result = conn.execute(sa.text("SELECT COUNT(*) FROM my_table WHERE ..."))
        if result.scalar() == 0:
            # Safe to insert/update
            pass
    """
    pass


def data_downgrade() -> None:
    """
    Rollback for data migrations executed with --x data=true.
    
    IMPORTANT: Be careful with data downgrades - they can cause data loss.
    Consider logging or backing up before deletion.
    """
    pass


def _should_run_data_migrations() -> bool:
    """Return True when the revision is invoked with ``--x data=true``."""
    x_args: dict[str, Any] = context.get_x_argument(as_dictionary=True)
    flag = x_args.get("data")
    if isinstance(flag, str):
        return flag.lower() in {"1", "true", "yes", "on"}
    return bool(flag)


# Helper function for manual idempotency checks if migration_helpers unavailable
def _table_exists(table_name: str) -> bool:
    """Fallback table existence check."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """Fallback column existence check."""
    if not _table_exists(table_name):
        return False
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {col['name'] for col in inspector.get_columns(table_name)}
    return column_name in columns

